version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${LL100_SHARED_DATA_DIR}/portal/nginx-proxy/nginx-html:/usr/share/nginx/html:ro
      - ${LL100_SHARED_DATA_DIR}/portal/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - ${LL100_SHARED_DATA_DIR}/portal/nginx-proxy/certs:/etc/nginx/certs:ro
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
