version: '3'

services:
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - ${LL100_SHARED_DATA_DIR}/portal/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ${LL100_SHARED_DATA_DIR}/portal/nginx-proxy/certs:/etc/nginx/certs:rw
      - ${LL100_SHARED_DATA_DIR}/portal/nginx-proxy/nginx-html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

