version: '3'

services:
  traefik:
    image: traefik:v2.5
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "8888:8888"
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
      - ./traefik/providers:/providers
      - ${LL100_SHARED_DATA_DIR}/global/acme.sh:/acme.sh

  nginx:
    image: nginx:1.21.3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.global-nginx.rule=HostRegexp(`{catch_all:.*}`) && PathPrefix(`/.well-known`)"
      - "traefik.http.routers.global-nginx.priority=999"
      - "traefik.http.services.global-nginx.loadbalancer.server.port=80"
    volumes:
      - ${LL100_SHARED_DATA_DIR}/global/nginx:/usr/share/nginx/html
    networks:
      - traefik

  whoami:
    image: traefik/whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-http.rule=HostRegexp(`{any:.*}`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami-http.entrypoints=web"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
