nginxproxy:
  image: jwilder/nginx-proxy:0.4.0
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - ${LL100_DATA_DIR}/ll100/nginx-proxy/vhost.d:/etc/nginx/vhost.d
    - ${LL100_DATA_DIR}/ll100/nginx-proxy/certs:/etc/nginx/certs


nginx:
  image: nginx:1.9.6
  restart: always
  volumes:
    - ./nginx-ll100.conf:/etc/nginx/conf.d/ll100.conf
    - ${LL100_DATA_DIR}/ll100/nginx/html:/usr/share/nginx/html
  environment:
    - VIRTUAL_HOST=www.ll100.com,support.ll100.com,dev.ll100.com
