mysql:
  image: mysql:5.5.42
  restart: always
  env_file: [ mysql_password.env ]
  volumes:
    - mysql-charset.cnf:/etc/mysql/conf.d/charset.cnf
    - ${LEAF_DATA_DIR}/mysql:/var/lib/mysql

redis:
  image: redis:2.8.19
  restart: always
  volumes:
    - ${LEAF_DATA_DIR}/redis:/data

app:
  build: .
  command: echo image container

deploy:
  image: leaf_app:latest
  links: [ mysql, redis ]
  restart: always
  environment:
    - ROLE=deploy
  volumes:
    - ${LEAF_DATA_DIR}/web-app:/home/app
    - ${LEAF_DATA_DIR}/log/nginx:/var/log/nginx
  ports:
    - "4022:22"

sidekiq:
  image: leaf_app:latest
  links: [ mysql, redis ]
  restart: always
  environment:
    - ROLE=sidekiq
  volumes:
    - ${LEAF_DATA_DIR}/web-app:/home/app

passenger:
  image: leaf_app:latest
  links: [ mysql, redis ]
  restart: always
  environment:
    - VIRTUAL_HOST=ll100.com,*.ll100.com
    - ROLE=passenger
  volumes:
    - ${LEAF_DATA_DIR}/web-app:/home/app
    - ${LEAF_DATA_DIR}/log/nginx:/var/log/nginx

sftp:
  image: leaf_app:latest
  restart: always
  env_file: [ sftp.env ]
  environment:
    - ROLE=sftp
  volumes:
    - ${LEAF_DATA_DIR}/web-app/shared/import:/home/app/shared/import
  ports:
    - "4023:22"

