mysql:
  image: mysql:5.5.42
  restart: always
  env_file: [ mysql_password.env ]
  volumes:
    - ${LEAF_DATA_DIR}/mysql:/var/lib/mysql

redis:
  image: redis:2.8.19
  restart: always
  volumes:
    - ${LEAF_DATA_DIR}/redis:/data

sidekiq:
  build: .
  links: [ mysql, redis ]
  restart: always
  environment:
    - ROLE=sidekiq
  volumes:
    - ${LEAF_DATA_DIR}/web-app:/home/app

nginx:
  build: .
  links: [ mysql, redis ]
  restart: always
  environment:
    - VIRTUAL_HOST=www.ll100.cn
    - ROLE=nginx
  volumes:
    - ${LEAF_DATA_DIR}/web-app:/home/app
  ports:
    - "4022:22"
    - "8081:80"

phpmyadmin:
  image: splattael/phpmyadmin:latest
  restart: always
  links: [ mysql ]
  ports: [ "8080:80" ]
