mysql:
  image: mysql:5.5.42
  restart: always
  # env_file: [ mysql_password.yml ] 
  volumes:
    - ../leaf-data/mysql:/var/lib/mysql

redis:
  image: redis:2.8.19
  volumes:
    - ../leaf-data/redis:/data

sidekiq:
  build: .
  links: [ mysql, redis ]
  restart: always
  environment:
    - ROLE=sidekiq
  volumes:
    - ../leaf-data/web-app:/home/app

nginx:
  build: .
  links: [ mysql, redis ]
  restart: always
  environment:
    - VIRTUAL_HOST=staging.ll100.cn
    - ROLE=nginx
  volumes:
    - ../leaf-data/web-app:/home/app
  ports:
    - "4022:22"
