wordpress:
  image: wordpress:4.2.3
  restart: always
  env_file: [ mysql_password.env ]
  environment:
    - VIRTUAL_HOST=blog.ll100.com,statics.blog.ll100cdn.com
    - CERT_NAME=blog.ll100.com
    - WORDPRESS_DB_HOST=192.168.100.3
  volumes:
    - ${LL100_SHARED_DATA_DIR}/blog/wordpress:/var/www/html
    - ./php.ini:/usr/local/etc/php/php.ini
