version: '2'

services:
  postgres:
    image: postgres:12.1
    restart: unless-stopped
    shm_size: 512m
    env_file: [ postgres_password.env ]
    volumes:
      - ${LL100_DATA_DIR}/db/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.7
    restart: unless-stopped
    volumes:
      - ${LL100_DATA_DIR}/db/redis:/data
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASS}
