[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.forwardedHeaders]
      insecure = true

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.forwardedHeaders]
      insecure = true

  [entryPoints.traefik]
    address = ":8888"

[api]
  insecure = true
  dashboard = true

[log]
  level= "DEBUG"

[certificatesResolvers.lets-encrypt.acme]
  email = "admin@ll100.com"
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[providers.docker]
  watch = true
  exposedByDefault=false
  network = "traefik"

[providers.file]
  watch = true
  directory="/providers"
