[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.forwardedHeaders]
      trustedIPs = ["192.168.0.0/24", "198.19.39.0/24"]

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.forwardedHeaders]
      trustedIPs = ["192.168.0.0/24", "198.19.39.0/24"]

  [entryPoints.traefik]
    address = ":8888"

[api]
  insecure = true
  dashboard = true

[log]
  level= "DEBUG"

[providers.docker]
  watch = true
  exposedByDefault=false
  network = "traefik"

[providers.file]
  watch = true
  directory="/providers"
