version: '2'

services:
  nginx:
    image: nginx:1.7.11
    restart: unless-stopped
    environment:
      - ROLE=nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apps-nginx-http.rule=Host(`apps.ll100.com`)"
      - "traefik.http.services.apps-nginx.loadbalancer.server.port=80"
    volumes:
      - ${LL100_SHARED_DATA_DIR}/apps/nginx/html:/usr/share/nginx/html
    networks:
      - traefik

networks:
  traefik:
    external: true
