nginx:
  image: nginx:1.7.11
  restart: always
  environment:
    - VIRTUAL_HOST=apps.ll100.com
    - HTTPS_METHOD=noredirect
    - ROLE=nginx
  volumes:
    - ${LL100_SHARED_DATA_DIR}/apps/nginx/html:/usr/share/nginx/html
