version: '2'

services:
  nginx:
    image: nginx:1.11.1
    restart: unless-stopped
    volumes:
      - ./nginx-ll100.conf:/etc/nginx/conf.d/ll100.conf
      - ${LL100_SHARED_DATA_DIR}/portal/nginx/html:/usr/share/nginx/html
    env_file: ./host.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal-nginx-http.rule=Host(`www.ll100.com`, `support.ll100.com`)"
      - "traefik.http.services.portal-nginx.loadbalancer.server.port=80"
    networks:
      - traefik

  ll100cn:
    image: nginx:1.11.1
    restart: unless-stopped
    volumes:
      - ./ll100cn-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ll100cn-index.html:/usr/share/nginx/html/index.html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal-ll100cn-http.rule=Host(`www.ll100.cn`, `ll100.cn`, `www.ll100.net`, `ll100.net`)"
      - "traefik.http.services.portal-ll100cn.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
