version: '2'

services:
  memcached:
    image: memcached:1.4.34
    restart: unless-stopped
    command: -m 2048

  deploy:
    extends:
      file: leaf.yml
      service: latest
    volumes:
      - ../leaf/40_enable_deploy.sh:/etc/my_init.d/40_enable_deploy.sh
    ports:
      - "4022:22"
    links:
      - memcached:memcached

  sidekiq:
    extends:
      file: leaf.yml
      service: latest
    environment:
      - APP_CURRENT_PATH=/home/app/www/backend/current
    volumes:
      - ../leaf/40_enable_sidekiq.sh:/etc/my_init.d/40_enable_sidekiq.sh
    links:
      - memcached:memcached

  frontend:
    extends:
      file: leaf.yml
      service: latest
    environment:
      - RAILS_SERVE_STATIC_FILES=yes
      - APP_CURRENT_PATH=/home/app/www/frontend/current
      - HTTPS_METHOD=noredirect
      - RAILS_MAX_THREADS=20
      - WEB_CONCURRENCY=6
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leaf-frontend.rule=Host(`${BASE_DOMAIN}`,`api.${BASE_DOMAIN}`,`p3.${BASE_DOMAIN}`, `gd.${BASE_DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.leaf-frontend.priority=1"
      - "traefik.http.services.leaf-frontend.loadbalancer.server.port=80"
    volumes:
      - ../leaf/40_enable_puma.sh:/etc/my_init.d/40_enable_puma.sh
    links:
      - memcached:memcached
    networks:
      - default
      - traefik

  wechat:
    extends:
      file: leaf.yml
      service: latest
    environment:
      - RAILS_SERVE_STATIC_FILES=yes
      - APP_CURRENT_PATH=/home/app/www/wechat/current
      - HTTPS_METHOD=noredirect
      - RAILS_MAX_THREADS=20
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leaf-wechat.rule=Host(`wx.${BASE_DOMAIN}`)"
      - "traefik.http.services.leaf-wechat.loadbalancer.server.port=80"
    volumes:
      - ../leaf/40_enable_puma.sh:/etc/my_init.d/40_enable_puma.sh
    links:
      - memcached:memcached
    networks:
      - default
      - traefik

  backend:
    extends:
      file: leaf.yml
      service: latest
    environment:
      - RAILS_SERVE_STATIC_FILES=yes
      - APP_CURRENT_PATH=/home/app/www/backend/current
      - HTTPS_METHOD=noredirect
      - WEB_CONCURRENCY=2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leaf-backend.rule=Host(`backend.${BASE_DOMAIN}`, `register.${BASE_DOMAIN}`)"
      - "traefik.http.services.leaf-backend.loadbalancer.server.port=80"
    volumes:
      - ../leaf/40_enable_puma.sh:/etc/my_init.d/40_enable_puma.sh
    links:
      - memcached:memcached
    networks:
      - default
      - traefik

  school:
    extends:
      file: leaf.yml
      service: latest
    environment:
      - RAILS_SERVE_STATIC_FILES=yes
      - APP_CURRENT_PATH=/home/app/www/school/current
      - WEB_CONCURRENCY=2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leaf-school.rule=Host(`school.${BASE_DOMAIN}`)"
      - "traefik.http.services.leaf-school.loadbalancer.server.port=80"
    volumes:
      - ../leaf/40_enable_puma.sh:/etc/my_init.d/40_enable_puma.sh
    links:
      - memcached:memcached
    networks:
      - default
      - traefik

  tingshuo:
    extends:
      file: leaf.yml
      service: latest
    environment:
      - RAILS_SERVE_STATIC_FILES=yes
      - APP_CURRENT_PATH=/home/app/www/tingshuo/current
      - WEB_CONCURRENCY=2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leaf-tingshuo.rule=Host(`wx.tsbang100.com`)"
      - "traefik.http.services.leaf-tingshuo.loadbalancer.server.port=80"
    volumes:
      - ../leaf/40_enable_puma.sh:/etc/my_init.d/40_enable_puma.sh
    links:
      - memcached:memcached
    networks:
      - default
      - traefik

  teacher:
    extends:
      file: leaf.yml
      service: latest
    restart: unless-stopped
    volumes:
      - ./teacher-nginx.conf:/etc/nginx/sites-enabled/default
      - ../leaf/40_enable_passenger.sh:/etc/my_init.d/40_enable_passenger.sh
    environment:
      - APP_CURRENT_PATH=/home/app/www/teacher/current
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leaf-teacher.rule=Host(`${BASE_DOMAIN}`) && PathPrefix(`/tb`)"
      - "traefik.http.services.leaf-teacher.loadbalancer.server.port=80"
    networks:
      - default
      - traefik

  student:
    extends:
      file: leaf.yml
      service: latest
    restart: unless-stopped
    volumes:
      - ./student-nginx.conf:/etc/nginx/sites-enabled/default
      - ../leaf/40_enable_passenger.sh:/etc/my_init.d/40_enable_passenger.sh
    environment:
      - APP_CURRENT_PATH=/home/app/www/student/current
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leaf-student.rule=Host(`${BASE_DOMAIN}`) && PathPrefix(`/sb`)"
      - "traefik.http.services.leaf-student.loadbalancer.server.port=80"
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true
