version: '2'

services:
  memcached:
    image: memcached:1.4.34
    restart: unless-stopped
    command: -m 2048

  deploy:
    extends:
      file: leaf.yml
      service: latest
    restart: unless-stopped
    environment:
      - ROLE=deploy
    ports:
      - "4022:22"
    links:
      - memcached:memcached

  sidekiq:
    extends:
      file: leaf.yml
      service: latest
    restart: unless-stopped
    environment:
      - ROLE=sidekiq
    links:
      - memcached:memcached

  passenger:
    extends:
      file: leaf.yml
      service: latest
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=ll100.com,*.ll100.com,*.ll100cdn.com
      - HTTPS_METHOD=noredirect
      - ROLE=passenger
    volumes:
      - ${LL100_LOCAL_DATA_DIR}/leaf/log/nginx:/var/log/nginx
    links:
      - memcached:memcached
    networks:
      - default
      - nginx-proxy

  # sftp:
  #   image: leaf_app:latest
  #   restart: unless-stopped
  #   env_file: [ sftp.env ]
  #   environment:
  #     - ROLE=sftp
  #   volumes:
  #     - ${LL100_DATA_DIR}/web/leaf/shared/import:/home/app/shared/import
  #   ports:
  #     - "4023:22"
  #

networks:
  nginx-proxy:
    external: true
