version: '2'

services:
  memcached:
    image: memcached:1.4.34
    restart: unless-stopped
    command: -m 2048

  deploy:
    extends:
      file: leaf.yml
      service: latest
    volumes:
      - ../leaf/40_enable_deploy.sh:/etc/my_init.d/40_enable_deploy.sh
    ports:
      - "4022:22"
    links:
      - memcached:memcached

  sidekiq:
    extends:
      file: leaf.yml
      service: latest
    environment:
      - APP_CURRENT_PATH=/home/app/www/backend/current
    volumes:
      - ../leaf/40_enable_sidekiq.sh:/etc/my_init.d/40_enable_sidekiq.sh
    links:
      - memcached:memcached

  frontend:
    extends:
      file: leaf.yml
      service: latest
    env_file: ./frontend-host.env
    environment:
      - RAILS_SERVE_STATIC_FILES=yes
      - APP_CURRENT_PATH=/home/app/www/frontend/current
      - HTTPS_METHOD=noredirect
      - RAILS_MAX_THREADS=20
      - VIRTUAL_PATH=/,/auth
    volumes:
      - ../leaf/40_enable_puma.sh:/etc/my_init.d/40_enable_puma.sh
    links:
      - memcached:memcached
    networks:
      - default
      - nginx-proxy

  wechat:
    extends:
      file: leaf.yml
      service: latest
    env_file: ./wechat-host.env
    environment:
      - RAILS_SERVE_STATIC_FILES=yes
      - APP_CURRENT_PATH=/home/app/www/wechat/current
      - HTTPS_METHOD=noredirect
      - RAILS_MAX_THREADS=20
    volumes:
      - ../leaf/40_enable_puma.sh:/etc/my_init.d/40_enable_puma.sh
    links:
      - memcached:memcached
    networks:
      - default
      - nginx-proxy

  backend:
    extends:
      file: leaf.yml
      service: latest
    env_file: ./backend-host.env
    environment:
      - RAILS_SERVE_STATIC_FILES=yes
      - APP_CURRENT_PATH=/home/app/www/backend/current
      - HTTPS_METHOD=noredirect
      - WEB_CONCURRENCY=2
    volumes:
      - ../leaf/40_enable_puma.sh:/etc/my_init.d/40_enable_puma.sh
    links:
      - memcached:memcached
    networks:
      - default
      - nginx-proxy

  school:
    extends:
      file: leaf.yml
      service: latest
    env_file: ./school-host.env
    environment:
      - RAILS_SERVE_STATIC_FILES=yes
      - APP_CURRENT_PATH=/home/app/www/school/current
      - WEB_CONCURRENCY=2
    volumes:
      - ../leaf/40_enable_puma.sh:/etc/my_init.d/40_enable_puma.sh
    links:
      - memcached:memcached
    networks:
      - default
      - nginx-proxy

  teacher:
    extends:
      file: leaf.yml
      service: latest
    restart: unless-stopped
    env_file: ./teacher-host.env
    volumes:
      - ./teacher-nginx.conf:/etc/nginx/sites-enabled/default
      - ../leaf/40_enable_passenger.sh:/etc/my_init.d/40_enable_passenger.sh
    environment:
      - APP_CURRENT_PATH=/home/app/www/teacher/current
      - VIRTUAL_PATH=/tb
    networks:
      - default
      - nginx-proxy

  student:
    extends:
      file: leaf.yml
      service: latest
    restart: unless-stopped
    env_file: ./student-host.env
    volumes:
      - ./student-nginx.conf:/etc/nginx/sites-enabled/default
      - ../leaf/40_enable_passenger.sh:/etc/my_init.d/40_enable_passenger.sh
    environment:
      - APP_CURRENT_PATH=/home/app/www/student/current
      - VIRTUAL_PATH=/sb
    networks:
      - default
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
