version: '2'

services:
  memcached:
    image: memcached:1.4.34
    restart: unless-stopped
    command: -m 2048

  deploy:
    extends:
      file: leaf.yml
      service: latest
    volumes:
      - ../leaf/40_enable_deploy.sh:/etc/my_init.d/40_enable_deploy.sh
    ports:
      - "4022:22"
    links:
      - memcached:memcached

  sidekiq:
    extends:
      file: leaf.yml
      service: latest
    environment:
      - ../leaf/40_enable_sidekiq.sh:/etc/my_init.d/40_enable_sidekiq.sh
      - APP_CURRENT_PATH=/home/app/www/backend/current
    links:
      - memcached:memcached

  frontend:
    extends:
      file: leaf.yml
      service: latest
    env_file: ./frontend-host.env
    environment:
      - APP_CURRENT_PATH=/home/app/www/frontend/current
      - HTTPS_METHOD=noredirect
      - RAILS_MAX_THREADS=20
      - VIRTUAL_PATH=/
    volumes:
      - ../leaf/40_enable_puma.sh:/etc/my_init.d/40_enable_puma.sh
      # - ${LL100_LOCAL_DATA_DIR}/leaf/log/frontend/nginx:/var/log/nginx
    links:
      - memcached:memcached
    networks:
      - default
      - nginx-proxy

  backend:
    extends:
      file: leaf.yml
      service: latest
    env_file: ./backend-host.env
    environment:
      - APP_CURRENT_PATH=/home/app/www/backend/current
      - HTTPS_METHOD=noredirect
      - WEB_CONCURRENCY=2
    volumes:
      - ../leaf/40_enable_puma.sh:/etc/my_init.d/40_enable_puma.sh
      # - ${LL100_LOCAL_DATA_DIR}/leaf/log/backend/nginx:/var/log/nginx
    links:
      - memcached:memcached
    networks:
      - default
      - nginx-proxy

  teacher:
    image: nginx:1.14.1
    restart: unless-stopped
    env_file: ./teacher-host.env
    environment:
      - VIRTUAL_PATH=/tb
    volumes:
      - ${LL100_LOCAL_DATA_DIR}/leaf/www:/home/app/www
      - ${LL100_LOCAL_DATA_DIR}/leaf/html/teacher:/usr/share/nginx/html
      # - ${LL100_LOCAL_DATA_DIR}/leaf/log/tewacher/nginx:/var/log/nginx
    networks:
      - default
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
