version: '2'

services:
  memcached:
    image: memcached:1.4.34
    restart: unless-stopped
    command: -m 2048

  deploy:
    extends:
      file: leaf.yml
      service: latest
    restart: unless-stopped
    environment:
      - ROLE=deploy
      - APP_CURRENT_PATH=/home/app/www/frontend/current
    ports:
      - "4022:22"
    links:
      - memcached:memcached

  sidekiq:
    extends:
      file: leaf.yml
      service: latest
    restart: unless-stopped
    environment:
      - ROLE=sidekiq
      - APP_CURRENT_PATH=/home/app/www/frontend/current
    links:
      - memcached:memcached

  passenger:
    extends:
      file: leaf.yml
      service: latest
    restart: unless-stopped
    env_file: ./host.env
    environment:
      - APP_CURRENT_PATH=/home/app/www/frontend/current
      - HTTPS_METHOD=noredirect
      - ROLE=passenger
    volumes:
      - ${LL100_LOCAL_DATA_DIR}/leaf/log/nginx:/var/log/nginx
    links:
      - memcached:memcached
    networks:
      - default
      - nginx-proxy

  # letsencrypt-cdn:
  #   image: busybox
  #   restart: unless-stopped
  #   environment:
  #     - LETSENCRYPT_HOST=statics.ll100cdn.com
  #     - LETSENCRYPT_EMAIL=admin@ll100.com
  #   command: sh -c "while [ true ]; do sleep 10; done"

networks:
  nginx-proxy:
    external: true
