version: '2'
services:
  latest:
    image: leaf_app:latest
    restart: always
    volumes:
      - ${LL100_LOCAL_DATA_DIR}/leaf/www:/home/app/www
      - ${LL100_SHARED_DATA_DIR}/leaf/shared:/home/app/shared
      - ${LL100_SHARED_DATA_DIR}/leaf/.ssh:/home/app/.ssh
