[http.routers.leaf-wechat]
  rule = "Host(`wx.staging.ll100.com`)"
  service = "leaf-wechat@docker"
  [http.routers.leaf-wechat.tls]
    certResolver="lets-encrypt"

[http.routers.leaf-frontend]
  rule = "Host(`staging.ll100.com`,`api.staging.ll100.com`,`p3.staging.ll100.com`) && PathPrefix(`/`)"
  service = "leaf-frontend@docker"
  priority=1
  [http.routers.leaf-frontend.tls]
    certResolver="lets-encrypt"

[http.routers.leaf-backend]
  rule = "Host(`backend.staging.ll100.com`, `register.staging.ll100.com`)"
  service = "leaf-backend@docker"
  [http.routers.leaf-backend.tls]
    certResolver="lets-encrypt"

[http.routers.leaf-school]
  rule = "Host(`school.staging.ll100.com`)"
  service = "leaf-school@docker"
  [http.routers.leaf-school.tls]
    certResolver="lets-encrypt"

[http.routers.leaf-student]
  rule = "Host(`staging.ll100.com`) && PathPrefix(`/sb`)"
  service = "leaf-student@docker"
  [http.routers.leaf-student.tls]
    certResolver="lets-encrypt"

[http.routers.leaf-teacher]
  rule = "Host(`staging.ll100.com`) && PathPrefix(`/tb`)"
  service = "leaf-teacher@docker"
  [http.routers.leaf-teacher.tls]
    certResolver="lets-encrypt"
